### ISSUE TITLE
Right Click is not working like expected 

### ISSUE THREAD

**Issue by freumichCH** [NastuzziSamy/files_rightclick#28]
Hello NastuzziSamy 

i've downloaded your App from the nextcloud AppStore on my NC13.0.5 instance. 
Unfortunately the Application is not working like expected. 

I get only the normal context menu of my Browser. On my Test instance does it work perfectly (same NC Version.)
![bildschirmfoto 2018-08-22 um 17 38 02](https://user-images.githubusercontent.com/22443781/44474119-2be7fe80-a632-11e8-9246-913ba70365d8.png)

do you have any idea where the Problem sits? 
i already tried to install it manually via the Download repo. 

Thanks in advance and keep up the great work! 😊

**Comment by RuudschMaHinda** [comment]
I have the same problem (with Firefox 62.0 64bit).

If you hold down Alt while right clicking the browser context menu disappears almost immediately. But that is a workaround I can hardly tell the people using the cloud. (They are not very tech savy, and any addition key that needs to be pressed gets them all confused unfortunately.)

**Comment by freumichCH** [comment]
That does unfortunaly not work for me. 
Is it a Problem if running behind a HAProxy?

**Comment by RuudschMaHinda** [comment]
From what I know this is happening on the browser side of things. So, unless the proxy server functions as some kind of "man in the middle" who changes the code of webpages (valid reason could be: ad-blocker - not valid reasons: countless) it shouldn't be about the proxy.
If it does do that, it also needs to strip the SSL-Certificate, which it shouldn't do, unless it is a corporation proxy - in that case, talk to the admin(s) of the proxy!

See if it works with different browsers. It worked for me in Chromium and Edge, which is why I was digging deeper into my Firefox settings and found the aforementioned configuration issue. If it works in different browsers for you as well, then it definitely is not the proxy, but the browser you are using.

**Comment by NastuzziSamy** [comment]
@freumichCH did you installed the last release ?

It is still happening ?
Let us know what you use (NC version ? OS ? Brower ? Browser version ? Do you have addons ?)

**Comment by NastuzziSamy** [comment]
Closing this due to inactiviy and lack of information
