### ISSUE TITLE
Nextcloud 15 compatibitity

### ISSUE THREAD

**Issue by violoncelloCH** [NastuzziSamy/files_rightclick#34]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by NastuzziSamy** [comment]
Hey, it will be in the next release :) (~ before Christmas, like I said in another issue)

**Comment by violoncelloch** [comment]
oh great! thank you :)

**Comment by GoetheG** [comment]
Really looking forward to it, @NastuzziSamy. You do a really great job. Your work is really appreciated here :).

**Comment by Schmuuu** [comment]
For the people who think this app is so awesome, who can hardly work with Nextcloud without it and can't wait for the next release: this app works flawlessly for me with NC15 after I edited appinfo/info.xml and changed the dependencies as follows:
```
<dependencies>
        <nextcloud min-version="13" max-version="15"/>
    </dependencies>
```

I made some further smaller changes so that `occ app:check-code` doesn't complain so much, but I think these changes were not necessary to make the app "work" again (so that it can be enabled again).

Anyway, I'm looking forward for the next release and a very big Thank you for this great app!

**Comment by nextgen-networks** [comment]
@NastuzziSamy Please consider this PR: https://github.com/NastuzziSamy/files_rightclick/pull/35
If everything went fine you could publish this to NC appstore too.
Thanks mate!

**Comment by elpraga** [comment]
Thank you for your work @NastuzziSamy ! I'm looking forward to the new release!

**Comment by NastuzziSamy** [comment]
Release for sunday at worth !

**Comment by stratege1401** [comment]
santa claus killed the update !!!

**Comment by NastuzziSamy** [comment]
@stratege1401 he actually killed me. 
No kidding, I am working on it

**Comment by stratege1401** [comment]
Yep, as i say Nasty Santa and his friends the hangover ...

**Comment by chiyi4488** [comment]
Happy New Year:DDDD

**Comment by immanuelfodor** [comment]
https://github.com/NastuzziSamy/files_rightclick/pull/35 has been merged, we should expect a new release soon! :tada:

**Comment by BloodyIron** [comment]
Posting so I can get in on the fun when it releases :D

**Comment by KopfKrieg** [comment]
@BloodyIron: You know there's a subscribe button, right?

**Comment by BloodyIron** [comment]
@KopfKrieg and you know the original post was 1 month ago to the day? (when I posted). Let's not argue over pedantic aspects. We all want to see this made available to nc15.

**Comment by KopfKrieg** [comment]
@BloodyIron I think you don't understand, my post was just a hint for you. Maybe I should have written "Please use the subscribe button next time". Let me explain why:

Posting without contributing anything to the related issue is considered bad behaviour and should be avoided. Every time someone posts in a topic/thread, everyone gets a notification for it. A notification, that is totally unnecessary and only wastes time of anyone subscribed to the discussion and makes the discussion hard to read.

That's why we have upvotes, downvotes, and the subscribe button. If you like an idea, upvote it. If you dislike an idea, downvote it. If you want to be notified if anything on a topic changes (e.g. the issue got resolved), subscribe to it.

That's all I wanted to say with my previous post.

**Comment by BloodyIron** [comment]
@KopfKrieg are you really picking a fight in a github ticket?... this is my hint to you. Stop.

**Comment by rcdailey** [comment]
Everyone is right, you need to stop @BloodyIron. Your behavior is very immature and probably violates community guidelines. I have gotten several emails today because of you, and it is disrupting my work. Please just stop.

**Comment by BloodyIron** [comment]
I guess I do need to defend myself here, which I think is completely ridiculous in a github ticket.

Let's see now, I posted because I wanted to sub and bump at the same time. This ticket is about slightly adjusting a nc addon to be compatible with nc15, and the original request was a month ago to the day from when I originally posted (yesterday).

Am I the only person who posted in a way that was "non-constructive" in this ticket? No.

Let's take a look at @chiyi4488 's post of "Happy New Year:DDDD"

How about @stratege1401 's post of "santa klaus killed the update !!!

Nasty santa"

Were those constructive? Are you guys jumping down their throat? No.

How about you guys stop harassing me over a single post I made and move on. You're calling me out about something but not calling anyone else out about the same thing. This doesn't matter, and I'm only responding because you guys clearly can't handle what I said. So I have to stand up for myself over something that's really not worth getting upset about in the first place.

You guys do whatever you're going to do, whether it's hypocrisy, punishment, or whatever. I don't regret what I did, and I for sure am not the only one in this ticket, _and countless other github tickets_ that have made posts of that ilk.

Grow up, move on, do whatever.

**Comment by BloodyIron** [comment]
@rcdailey hey, I noticed you immediately downthumbed me right after posting. No way you could have actually read what I wrote in that time. Thanks guy, classy.

**Comment by rcdailey** [comment]
In my mind, people are reacting to your defensiveness and immaturity to the issue, not necessarily that you bumped it. You could have accepted the advice, moved on, and done better next time, but you didn't. And yes, I did read your post before downvoting. But to be honest, part of me already knew how you were going to reply.

I get that you are angry. Take some time to cool off. No one is attacking you personally. This is all part of good etiquette on Github. It takes all of us following the rules and being respectful to one another for this system to work.

**Comment by BloodyIron** [comment]
@rcdailey I don't like that I'm being treated unequally to others. I'm being called out for activity others have literally done in this thread and that's not fair. How exactly am I supposed to feel when treated like that? Would you feel any differently? I doubt it.

**Comment by BloodyIron** [comment]
fuck it, clearly not welcome here, bye dickwads, maybe recheck how you responded to me if you think you're so on the level here..

**Comment by NastuzziSamy** [comment]
Wow guys calm down ^^

Do not force me to lock down this conversation.
As I got a time for me, I will release the compatible version in less a week.

**Comment by BloodyIron** [comment]
seriously in all my github dealings I have never been treated with such hostility, you guys take the cake

**Comment by rcdailey** [comment]
At this point I would recommend we all just stop replying to @BloodyIron. Just ignore him and hopefully conversation dies down. Apologies for adding to the disruption.

**Comment by NastuzziSamy** [comment]
> fuck it, clearly not welcome here, bye dickwads, maybe recheck how you responded to me if you think you're so on the level here..

No need for this here or in any Github repo.

@BloodyIron, stop arguing pls, you are welcome like others, to contribute, to follow and to discuss on issue subjects.

**Comment by stratege1401** [comment]
They clearly dont belong here ... fuck is not a coding variable !!! 

The with house forum may be available for this, not github community ( community = A group of people living together and practising common ownership with boundaries and respect )

**Comment by violoncelloCH** [comment]
@NastuzziSamy as you are the owner of this repo I would suggest you just hide all of those offensive comments, regardless from which party... thank you for your work!

**Comment by NastuzziSamy** [comment]
🎉 It's released ! \o/

=> https://apps.nextcloud.com/apps/files_rightclick

**Comment by GoetheG** [comment]
Vielen Dank!

**Comment by edo0** [comment]
Thank you very much!!
